<?xml version="1.0" ?>
<!DOCTYPE addressbook [
<!ELEMENT addressbook (person+)>
<!ELEMENT person (name,e-mail+)>
<!ELEMENT name (#PCDATA|family|given)*>
<!ELEMENT family (#PCDATA)>
<!ELEMENT given (#PCDATA)>
<!ELEMENT e-mail (#PCDATA)>
]>
<addressbook>
<person>
<name>
<family>kafatos</family>
<given>Fotis</given>
</name>
<e-mail>fotis@embl.de</e-mail>
</person>

<person>
<name>
<family>Cameron</family>
<given>Graham</given>
</name>
<e-mail>cameron@ebi.ac.uk</e-mail>
</person>

<person>
<name>
<family>Ahburner</family>
<given>Michael</given>
</name>
<e-mail>Ahburner@ebi.ac.uk</e-mail>
</person>

<person>
<name>
<family>Alan</family>
<given>Robinson</given>
</name>
<e-mail>fotis@ebi.ac.uk</e-mail>
</person>

<person>
<name>
<family>Patricia</family>
<given>Rodriguez-Tome</given>
</name>
<e-mail>Tome@ebi.ac.uk</e-mail>
</person>

<person>
<name>
<family>Adams</family>
<given>Gillian</given>
</name>
<e-mail>adams@ebi.ac.uk</e-mail>
</person> 
</addressbook>