=== deezell1002/XML/ข้อสอบ MIDTERM XML/5506021610128/reciept.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
targetNamespace="www.pexam.com/receipt"
xmlns="www.pexam.com/receipt" elementFormDefault="qualified">

<xs:element name="receipt">
<xs:complexType>
<xs:sequence>

<xs:element name="date">
<xs:complexType>
<xs:sequence>

<xs:element name="day">
<xs:simpleType>
<xs:restriction base="xs:integer">
<xs:minInclusive value="1"/>
<xs:maxInclusive value="31"/>
</xs:restriction>
</xs:simpleType>
</xs:element>

<xs:element name="month">
<xs:simpleType>
<xs:restriction base="xs:integer">
<xs:minInclusive value="1"/>
<xs:maxInclusive value="12"/>
</xs:restriction>
</xs:simpleType>
</xs:element>

<xs:element name="year">
<xs:simpleType>
<xs:restriction base="xs:integer">
<xs:minInclusive value="2550"/>
<xs:maxInclusive value="2560"/>
</xs:restriction>
</xs:simpleType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="address">
<xs:complexType>
<xs:sequence>

<xs:element name="shop" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="numberhome" type="xs:string"/>
<xs:element name="moo" type="xs:string"/>
<xs:element name="area" type="xs:string"/>
<xs:element name="tambon" type="xs:string"/>
<xs:element name="amphor" type="xs:string"/>
<xs:element name="chanwat" type="xs:string"/>

</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="item" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="order" type="xs:string"/>
<xs:element name="price" type="xs:integer"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="total" type="xs:integer"/>

</xs:sequence>
<xs:attribute name="id" use="required">
<xs:simpleType>
<xs:restriction base="xs:integer">
<xs:pattern value="[0-9][0-9][0-9]"/>
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>
</xs:schema>

=== deezell1002/XML/ข้อสอบ MIDTERM XML/5506021610128/receipt.xml
<?xml version="1.0"?>
<receipt id="109"
xmlns ="www.pexam.com/receipt"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="www.pexam.com/receipt reciept.xsd">
<date>
<day>29</day>
<month>07</month>
<year>2557</year>
</date>

<address>
<shop>shop</shop>
<name>april</name>
<numberhome>202</numberhome>
<moo></moo>
<area>street road</area>
<tambon>bang pha</tambon>
<amphor>Muang</amphor>
<chanwat>Prachinburi</chanwat>
</address>


<item>
<order>pens</order>
<price>120</price>
</item>

<item>
<order>book</order>
<price>350</price>
</item>

<item>
<order>pen</order>
<price>14</price>
</item>

<total>484</total>



</receipt>
